# This is a basic workflow to help you get started with Actions
name: Logseq Deploy

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel

permissions:
    contents: write

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Publish action by other contributor
      - name: Logseq Publish
        uses: logseq/publish-spa@v0.3.0

      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
          
      # Set up Node.js v20 for Firebase deployment
      - name: Setup Node.js for Firebase
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: deploy to firebase hosting live channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTE_E3304 }}"
          projectId: note-e3304
          channelId: live
